FROM {{ namespace }}/{{ image_prefix }}ironic-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
        tftp-server \
        syslinux-tftpboot \
    && yum clean all

{% elif base_distro in ['ubuntu', 'debian'] %}

{% if base_distro_tag in ['ppc64'] %}

RUN apt-get update \ 
     && apt-get -y install --no-install-recommends \
        tftpd-hpa \
        syslinux-common \
    && apt-get clean

{% else %}

RUN apt-get -y install --no-install-recommends \
        tftpd-hpa \
        syslinux-common \
        syslinux \
    && apt-get clean

{% endif %}
{% endif %}

COPY tftp-map-file /map-file
COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{{ include_footer }}
