FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

# Install required packages
RUN yum -y install \
        openstack-neutron-openvswitch \
        openvswitch \
    && yum clean all

    {% elif base_distro in ['ubuntu'] %}

{% if base_distro_tag in ['ppc64'] %}

RUN apt-get update

{% endif %}

RUN apt-get -y install --no-install-recommends \
        openvswitch-switch \
        neutron-plugin-openvswitch-agent \
    && apt-get clean

    {% endif %}
{% endif %}

{{ include_footer }}

USER neutron
