FROM {{ namespace }}/{{ image_prefix }}nova-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% set libvirt_group = 'libvirtd' %}

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
        libvirt-daemon \
        libguestfs \
        qemu-system-x86 \
        libvirt-daemon-driver-nwfilter \
        libvirt-daemon-config-nwfilter \
        libvirt-daemon-driver-lxc \
        ceph-common \
    && yum clean all \
    && usermod -a -G nova qemu


{% elif base_distro in ['ubuntu', 'debian'] %}

{% if base_distro == 'ubuntu' %}
{% if base_distro_tag in ['ppc64'] %}
RUN /bin/true
{% else %}
{% set packages =
      ' xen-utils-4.6'
%}
{% endif %}
{% elif base_distro == 'debian' %}
{% set packages =
      ' xen-utils-4.4 usermode'
%}
{% set libvirt_group = 'libvirt' %}
{% endif %}

{% if base_distro_tag in ['ppc64'] %} 

RUN apt-get update \
    && apt-get install -y --no-install-recommends \ 
        ceph-common \ 
        libvirt-bin \ 
        pm-utils \ 
        qemu \ 
        qemu-block-extra \ 
        ebtables \ 
    && apt-get clean \ 
    && mkdir -p /etc/ceph \ 
    && rm /etc/libvirt/qemu/networks/default.xml /etc/libvirt/qemu/networks/autostart/default.xml \
    && usermod -a -G {{ libvirt_group }} nova

COPY libvirt_sudoers /etc/sudoers.d/libvirt_sudoers

RUN chmod 440 /etc/sudoers.d/libvirt_sudoers

{% else %}

RUN apt-get -y install --no-install-recommends \
        ceph-common \
        libvirt-bin \
        dmidecode \
        pm-utils \
        qemu \
        qemu-block-extra \
        ebtables \
        {{ packages }} \
    && apt-get clean \
    && mkdir -p /etc/ceph \
    && rm -f /etc/libvirt/qemu/networks/default.xml /etc/libvirt/qemu/networks/autostart/default.xml \
    && usermod -a -G {{ libvirt_group }} nova

{% endif %}
{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start
 
{{ include_footer }}
