FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
        openstack-neutron-lbaas \
    && yum clean all

    {% elif base_distro in ['ubuntu'] %}

RUN apt-get -y install --no-install-recommends \
        neutron-lbaas-common \
        neutron-lbaasv2-agent \
        python-neutron-lbaas \
    && apt-get clean \
    {% endif %}
{% endif %}

{% if base_distro_tag in ['ppc64'] %}

RUN rm /etc/neutron/api-paste.ini \
    /etc/neutron/policy.json \
    /etc/neutron/rootwrap.conf \
    /etc/sudoers.d/neutron_sudoers

RUN apt-get update \
    && apt-get -y install --no-install-recommends \
        neutron-lbaas-common \
        neutron-lbaasv2-agent \
        python-neutron-lbaas \
    && apt-get clean \

{% endif %}

ADD plugins-archive /
COPY extend_start.sh /usr/local/bin/kolla_neutron_extend_start
RUN chmod 755 /usr/local/bin/kolla_neutron_extend_start \
    && if [ "$(ls /plugins)" ]; then \
           pip --no-cache-dir install --upgrade -c requirements/upper-constraints.txt /plugins/*; \
       fi

{{ include_footer }}

USER neutron
