FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

# Since the gate cannot do DinD on centos due to the age of the kernel, we don't
# build a true DinD image. Should the time come that we get a newer kernel in
# the centos gate and we want to do multinode we can populate this container
RUN /bin/true

{% elif base_distro in ['ubuntu', 'debian'] %}

{% if base_distro_tag in ['ppc64'] %}

RUN apt-get update \
    && apt-get -y install --no-install-recommends \
        iptables \
        btrfs-tools \
        openssh-server \
        python-pip \
        wget \
    && apt-get clean \
    && pip install --upgrade docker-py

RUN mkdir docker \
    && cd docker ; wget ftp://ftp.unicamp.br/pub/linuxpatch/docker-ppc64/ubuntu/14_04/docker.io-1.4.1-dev_ppc64el.deb \
    && dpkg -i docker.io-1.4.1-dev_ppc64el.deb

{% else %}

RUN apt-get update \
    && apt-get -y install --no-install-recommends \
        btrfs-tools \
        docker-engine \
        openssh-server \
    && apt-get clean \
    && pip --no-cache-dir install --upgrade docker-py

{% endif %}
{% endif %}

COPY start.sh /usr/local/bin/kolla_start
RUN chmod 755 /usr/local/bin/kolla_start

{{ include_footer }}
