FROM {{ namespace }}/{{ image_prefix }}trove-base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if base_distro_tag in ['ppc64'] %}

RUN /bin/true

{% else %}


{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'fedora', 'oraclelinux', 'rhel'] %}

RUN yum -y install \
        openstack-trove-taskmanager \
  && yum clean all

    {% elif base_distro in ['ubuntu'] %}

RUN  apt-get update  \ 
    && apt-get -y install --no-install-recommends \
        trove-taskmanager \
    && apt-get clean

    {% endif %}
{% endif %}
{% endif %}

{{ include_footer }}

USER trove
